### ISSUE TITLE
Remove 0.1 branch

### ISSUE THREAD

**Issue by cle1109** [scot-dev/scot#101]
We won't be supporting (updating) old versions, so there's no need to clutter our list of branches.

**Comment by mbillingr** [comment]
That's right.

**Comment by cle1109** [comment]
So can I go ahead and delete it?

**Comment by mbillingr** [comment]
Yes, this should be safe. 

In case, we loose the tag, this is the 0.1.1 commit: c3e76d3884aba127fe08f5e4a3000a38b95e866c
