### ISSUE TITLE
0.2 Release

### ISSUE THREAD

**Issue by mbillingr** [scot-dev/scot#102]
We're almost done. Only #30 and #94 (well, and #102) remain at the moment.

Is there anything else that should go into the 0.2 release?

**Comment by cle1109** [comment]
#62 would be great - it is really annoying to have the example data for the tests in a separate package.

**Comment by mbillingr** [comment]
Work on #62 has not even really started, yet. I've only defined the API, but there is no actual code.

We can include it in 0.2, but that will delay the release a bit.

**Comment by cle1109** [comment]
Then let's release 0.2 without the downloader and schedule #62 for the next version.

**Comment by mbillingr** [comment]
OK

**Comment by mbillingr** [comment]
What about #97, #79, #66, #53, #52, #14, #3, and #2?

**Comment by cle1109** [comment]
#3, #14, #52 could go into 0.2 if they are not too much work. We could solve one half of #97 via #59 (initialize weight with identity matrix for FastICA). If you have a suggestion how to fix the Infomax overflow issue, we could include #97 in 0.2. Otherwise, I would postpone #97 and the rest for the next release.

**Comment by mbillingr** [comment]
I have added #14 and #52 to the Milestone. Let's postpone #97.
Concerning #3, I can't remember what the bug was, and the description is not very informative :)

**Comment by cle1109** [comment]
We need to update our documentation to reflect the changes in the API. We should also state this prominently on the main docs page and the release notes.

**Comment by mbillingr** [comment]
Good idea!

**Comment by cle1109** [comment]
- [ ] Update docs, create release notes, etc.
- [ ] #30
- [ ] #52

**Comment by cle1109** [comment]
What do we do next?

**Comment by mbillingr** [comment]
Once we got coverage to 90% we're done, right?

**Comment by cle1109** [comment]
Yes! After we merge #99, I will change the version string in #113, build the docs, and you can go ahead and release 0.2.

**Comment by mbillingr** [comment]
We have the Github release: https://github.com/scot-dev/scot/releases

Now we can update the docs. What about pypy?

**Comment by cle1109** [comment]
Yes, we should update our PyPI package too. Were you the one doing that :-)?

Also: how do we close the 0.2 milestone?

And: please take a look at the doc website - the style has changed. It's a bit ugly, so we might have to change the style in the future. Even worse, the badges at the bottom show 87% coverage and build error! We need to fix that - do you know how?

**Comment by mbillingr** [comment]
I thought you were doing the pypi thing? :)

Also: Most likely it will close automatically when all issues and PRs are done.

Style: Ugly, but works

Badges: I'm on it

**Comment by cle1109** [comment]
* PyPI: No, the site says you're the owner: https://pypi.python.org/pypi/scot/0.1.0
* Milestones: Let's wait and see. Otherwise, we'll have to delete it manually (or maybe there's a way to close it manually).
* Style: Yes, it works, but it's much worse than before. The vertical bars in the top and bottom menu are not even separated from the preceding words (home| examples| gallery| search). Ugly as hell.
* Thanks. They seem to point to the correct locations (master branches), but Coveralls doesn't show the new coverage at the top. And I have no idea what's wrong with Travis (why is there an issue with #113?).

**Comment by mbillingr** [comment]
- I'll look into pypi.
- Can you try to improve the doc style?
- I think the badges fail because I disabled push tests in travis so we have no update on the master branch.

**Comment by cle1109** [comment]
I have some notes on how to make a PyPI release lying around - let me know if you need them. I'll try to change the website style.

I don't understand your last point - we see all updates in the master branch.

**Comment by mbillingr** [comment]
Travis did not run tests on "push" events, only on the pull requests. I think this also means that no tests were run after merging the PR. In consequence the status of the master branch was never updated.

**Comment by cle1109** [comment]
And how did you change this behavior now?

**Comment by mbillingr** [comment]
A few days ago, I disabled the checkbox on the travis site when you complained about two tests in one of the PRs.

I switched it back on, now.

Behold the updated badges in the docs! :)

**Comment by cle1109** [comment]
> A few days ago, I disabled the checkbox on the travis site when you complained about two tests in one of the PRs.
> 
> I switched it back on, now.

Which checkbox? I'm confused. And how did you solve the Coveralls issue?

> Behold the updated badges in the docs! :)

Nice. Now that they're working, I would remove them and put them in our GitHub `README.md` :-). The docs should not show the current build and coverage status IMO.

**Comment by mbillingr** [comment]
> Which checkbox? I'm confused. 

There is a settings dialog at the travis site. Maybe you have to be logged in to see it?
https://travis-ci.org/scot-dev/scot/settings

> And how did you solve the Coveralls issue?

There is no separate travis issue. The Python 3 tests record coverage and send the result to coveralls. If there is no test run on a push, there is also no up-to-date coverage report.

**Comment by mbillingr** [comment]
> Nice. Now that they're working, I would remove them and put them in our GitHub README.md :-). The docs should not show the current build and coverage status IMO.

Why did you remove them from the README in the first place?

**Comment by cle1109** [comment]
Did I? Unintentionally. Let's add them back and remove them from the website docs.

**Comment by mbillingr** [comment]
See here: edd3c91193767e7ebb8525fd435c48feea904861

**Comment by cle1109** [comment]
Yes, my mistake.

**Comment by mbillingr** [comment]
OK. Can you fix it?

And do you have the pypi notes at hand?

**Comment by mbillingr** [comment]
Nevermind pypi notes, it's done: https://pypi.python.org/pypi/scot/0.2

Strangely, pypi reports 0.2 as the latest version. However, pip does not:

    scot             - EEG/MEG Source Connectivity Toolbox
      INSTALLED: 0.2
      LATEST:    0.1.0

**Comment by cle1109** [comment]
> OK. Can you fix it?

#117

**Comment by cle1109** [comment]
> Strangely, pypi reports 0.2 as the latest version. However, pip does not:

How did you create this pip output?

**Comment by mbillingr** [comment]
First I did `pip install scot --upgrade`

Then `pip search scot` produced this output.

**Comment by cle1109** [comment]
That's weird. Maybe it's because we're comparing a two-digit vs. a three-digit number? Or it might be a pip bug...

**Comment by mbillingr** [comment]
Looks like we messed up the 0.2 release.

I was able to apply the hotfix #118/#119 before the 0.2 commit in the history. This is fine in the repository. However, there is no way to replace a release on PyPI. This means we cannot simply fix the PyPI release.

I decided to delete 0.2 on PyPI but keep the 0.2 release on GitHub and put it on PyPI as 0.2.1.

I have also created an additional 0.2.1 release on GitHub so we have a direct correspondence between the PyPI package and the repository. Apart from the version number the releases 0.2 and 0.2.1 are identical.

**Comment by cle1109** [comment]
Thanks @mbillingr - `pip` still shows 0.1.0 as the latest version. Maybe there's an option to tag a release as the latest version.

Independently of this issue, do you think we should always use 3-digit version numbers?

**Comment by mbillingr** [comment]
I think 3-digit version numbers are ugly, Especially since we don't plan to keep release branches.

**Comment by cle1109** [comment]
OK - so I guess we're finally done with the 0.2, I mean 0.2.1 release :-).
