### ISSUE TITLE
Add GUI

### ISSUE THREAD

**Issue by cbrnr** [scot-dev/scot#111]
I think a GUI would make SCoT more accessible to non-programmers. We could implement a standard analysis pipeline, where everything can be carried out via mouse clicks.

This is something for the not-so-near future, so I'm not going to start discussing the details now. Only one thing: we should use PyQt/PySide :-).

**Comment by mbillingr** [comment]
I agree with PyQt.

What about preprocessing? SCoT does not have and should not have many EEG preprocessing capabilities. How should the GUI be interfaced to other packages that provide such functionality?

**Comment by cle1109** [comment]
Loading data files should either use `scipy.io` or routines from MNE-Python. Most preprocessing steps are already covered by Scipy. For missing stuff, we can use MNE-Python. However, I can't think of a preprocessing technique that's not available in Scipy - can you?

**Comment by mbillingr** [comment]
There are 1000s ways of applying the same technique. Just take mean removal as an example. You can subtract the signal mean, or the epoch mean, or a baseline, or you can use a high-pass, ...

I'm sure we don't want to wrap every possible technique from scipy in the GUI, and we don't want SCoT to become another EEGLAB.

Also, it does not make sense to provide a GUI for non-programmers and tell them to use scipy to prepare the data first :)

What I'm trying to say, we must be very precise about stating the scope and purpose of the GUI, and have clear ideas how the GUI fits into the non-programmer's toolchain.

**Comment by cle1109** [comment]
Right. Maybe it's not such a great idea after all. The GUI would need to offer only a limited set of functions. I think you can achieve quite a lot with basic preprocessing and what's already there in SCoT. But like I said, I just put this up to have a general discussion if a GUI makes sense at all. Don't you think that we could already wrap a basic pipeline into a GUI? Like load a data set, epoch it, compute ICs, and compute connectivity among ICs.

**Comment by mbillingr** [comment]
I think that's possible. Would it make sense to skip the epoch step and start the pipeline with 3D epoched data?

**Comment by cle1109** [comment]
Hm. We do have functionality to create epoched data, so why do you want to skip this step?

**Comment by mbillingr** [comment]
I'm not entirely sure what I don't like about it. Just a gut feeling, so to speak. Let's make it optional :)

**Comment by cle1109** [comment]
Yes. I think you should be able to enter the pipeline either with continuous data or skip this step and directly start with epoched data.

**Comment by cbrnr** [comment]
Let's skip the whole GUI idea for now and focus on getting the toolbox in shape on the scripting level.
