### ISSUE TITLE
scot.ini isn't installed

### ISSUE THREAD

**Issue by cle1109** [scot-dev/scot#118]
@mbillingr can you please create a hotfix? It's probably missing in the PyPI config.

**Comment by mbillingr** [comment]
Where do we add it? `setup.py`?

**Comment by cle1109** [comment]
I guess: https://pythonhosted.org/setuptools/setuptools.html#including-data-files

**Comment by mbillingr** [comment]
OK, it's fixed. But we've released already. What do we do now?

**Comment by cle1109** [comment]
Can we update our 0.2 release? I don't want to release 0.2.1 because of this. Makes us look like idiots :-).

**Comment by mbillingr** [comment]
Hehe.. let's time travel again :p

**Comment by cle1109** [comment]
OK, can you go ahead and re-upload to PyPI?

**Comment by cle1109** [comment]
And re-create the release?
