### ISSUE TITLE
pip shows 0.1.0 as latest version

### ISSUE THREAD

**Issue by cle1109** [scot-dev/scot#121]
This happened after we released 0.2 and 0.2.1. Maybe it will go away, let's check back after some time. If not, we should probably do something about it.

**Comment by mbillingr** [comment]
But it installs the correct version.

**Comment by cle1109** [comment]
Yes, that's why I suspect it might only be a temporary issue. Still, if it doesn't disappear we should look into it - other packages work normally.

**Comment by cle1109** [comment]
Let's see if the pip folks know what's going on - https://github.com/pypa/pip/issues/3474

**Comment by cle1109** [comment]
Closing this because it is just the slow API of PyPI, so this will likely be resolved automatically soon.

**Comment by mbillingr** [comment]
At least we hope it's the API and not my having screwed up at pypi.
