### ISSUE TITLE
Avoid overfitting

### ISSUE THREAD

**Issue by cle1109** [scot-dev/scot#131]
I was wondering if certain procedures generalize to unseen data. For example, can I use the whole data for model order selection? Can I use the whole data for optimizing the regularization parameter? What if the whiteness test is significant and I need to go back and choose a higher model order? What if I need to do this a couple of times until the test is not significant?

Are there other situations where it is important to use appropriate procedures to prevent overfitting?

Does SCoT already have mechanisms to prevent overfitting (e.g. via CV)? @mbillingr?

**Comment by mbillingr** [comment]
Internally, we avoid overfitting by optimizing the *mean squared generalization error (MSGE)* in model selection (order and regularization).

If you reiterate over the whole data until your whiteness test becomes non-significant, you may be overfitting in some way. I have no idea if this is a problem, or how to frame this in CV.

**Comment by cle1109** [comment]
A quick reminder, how exactly is the MSGE defined?

**Comment by mbillingr** [comment]
It's the variance of cross-validated residuals.

**Comment by cle1109** [comment]
OK. Is the exact nature of the CV important (how many folds)? What does SCoT use? Can/should it be changed?

So I guess we'd need to use the MSGE in AIC/BIC/FPE-based model order selection as well, right? This would make these procedures much slower, maybe just as slow as the CV-based procedure we already have...

**Comment by mbillingr** [comment]
SCoT uses either leave-one-out (default) or single-trial-fitting. I don't think it needs to be changed, but we could try to support scikit-learn's cross validation objects.

> So I guess we'd need to use the MSGE in AIC/BIC/FPE-based model order selection as well, right?

No, I think these selection criteria are meant to be used instead of cross-validation. They explicitly penalize model complexity, while the MSGE implicitly does that.

This discussion reminds me why AIC/etc were not implemented in the first place. The way these criteria penalize model order is only valid for simple linear regression. If you start to use regularization they become too conservative.

**Comment by cle1109** [comment]
> SCoT uses either leave-one-out (default) or single-trial-fitting. I don't think it needs to be changed, but we could try to support scikit-learn's cross validation objects.

Yep, maybe a good idea for the future.

> No, I think these selection criteria are meant to be used instead of cross-validation. They explicitly penalize model complexity, while the MSGE implicitly does that.

Thanks, this also answers my question over at #130. That's what I thought.

> This discussion reminds me why AIC/etc were not implemented in the first place. The way these criteria penalize model order is only valid for simple linear regression. If you start to use regularization they become too conservative.

Correct, but the default is no regularization. We already have our first recommendation/default!

**Comment by cle1109** [comment]
cf #132

**Comment by mbillingr** [comment]
> Correct, but the default is no regularization. We already have our first recommendation/default!

True :)

In the past I have adviced to generously select a high model order and then optimize regularization.

An alternative is to forgo regularization and optimize model order with AIC/etc.

I don't know if selecting regularization with subsequent optimization of the model order is a useful usecase, unless you want to iterate these steps.

**Comment by cle1109** [comment]
Nah, I also view these two strategies as mutually exclusive. You either optimize regularization (and choose a high model order), or you optimize model order (and do not regularize). The combination of these two steps might be useful in theory, but for now I'd keep it simple.

**Comment by cle1109** [comment]
BTW, is it correct to think of VAR regularization as restricting the model order to small values? After all, the model order is the only parameter a VAR model has...

**Comment by mbillingr** [comment]
This also means that AIC/etc suddenly became useful for us ;)

**Comment by mbillingr** [comment]
BTW, is it correct to think of VAR regularization as restricting the model order to small values?

No, but the other way round. You can think of model order selection as a special kind of regularization.

Don't forget that the model order is just a *hyperparameter* of the AR model.
Regularization restricts the model coefficients to small values.

If you select a model order you basically restrict coefficients above a certain lag to be equal 0, which you could view as regularization.

**Comment by cle1109** [comment]
Of course, this makes sense. So by using linear models with L1 regularization from scikit-learn,  we can also force coefficients to be exactly 0. (We only implement L2 regularization, right?)

**Comment by mbillingr** [comment]
Exactly.
