### ISSUE TITLE
Do we need return values for do_mvarica and do_cspvarica?

### ISSUE THREAD

**Issue by cle1109** [scot-dev/scot#137]
I was wondering if we really need return values for the functions `do_mvarica` and `do_cspvarica`. Somehow, I expect these functions to store the computed values in the `Workspace` object (which they do) - so why do they need to return the results as well?

**Comment by mbillingr** [comment]
Good question. I think you are right.

**Comment by cle1109** [comment]
The returned `Result` object (wouldn't a `dict` be more Pythonic BTW?) might actually contain more information. Can you please verify that everything we need is stored in the `Workspace` object before we drop the return statement?

**Comment by mbillingr** [comment]
The `Result` contains a bit more than what is stored in the workspace, but these extra results are usually not needed.

The examples don't even use the return value, so I think it's safe to drop it.
