### ISSUE TITLE
Coveralls

### ISSUE THREAD

**Issue by mbillingr** [scot-dev/scot#154]
Any idea why we no longer get coverage reports from Coveralls?

**Comment by cbrnr** [comment]
No - did we change a relevant config file? I guess you need to grant access to Coveralls in order to let it post inside PRs - where do you do that? Is there some kind of access token/key that needs to be set?

**Comment by mbillingr** [comment]
Coveralls is authorized to access my Github account (OAuth settings). There should not be anything else to do.

There is a repository token for scot at the coveralls page, but I don't know what to do with it.

**Comment by cbrnr** [comment]
This sounds like black magic. Did we change anything recently? Is there a config file for Coveralls? It seems like Travis triggers Coveralls and Coveralls is working, so either Coveralls doesn't have access anymore (are there Coveralls logs somewhere?) or it just stopped working (or something changed and now works differently).

**Comment by mbillingr** [comment]
Neither sklearn nor mne-python seem to get any report from Coveralls. (But they don't seem to care?)

Maybe Coveralls is just buggy and we should try to find a different system. (Maybe there is one that's better documented?)

**Comment by cbrnr** [comment]
Hehe - yes, there should be plenty of these services around. I never found Coveralls particularly straightforward either. What about https://codecov.io/?

**Comment by mbillingr** [comment]
Codecov could be promising. I've tried to set it up for libGDF once, but failed to get coverage from C++.

**Comment by cbrnr** [comment]
Do you want to give it a try?
