### ISSUE TITLE
Is channel space DTF the same as source space DTF?

### ISSUE THREAD

**Issue by mbillingr** [scot-dev/scot#162]
We'll discuss this elsewhere.

**Comment by cbrnr** [comment]
I just started a similar toy simulation :-). This is of course expected, but maybe not sufficient for an unbiased answer to this question. Here, we assume that ICA sources are the ground truth, but we don't actually know how well ICA is able to separate these sources from measured EEG.

Therefore, I think a simulation involving a realistic forward model would be even better. Here's what I'd do:

1. Create 3 sources with known connectivity structure from a VAR model
2. Transform these sources to 64 EEG channels with a realistic forward model
3. Estimate DTF from the EEG channels
4. Apply ICA to the EEG channels, and estimate DTF from ICA sources
5. Compare with the ground truth DTF of original sources

What do you think? Here's the code I have so far:

```Python
import numpy as np
from scot.var import VAR
from scot.connectivity import connectivity
from scot.plotting import plot_connectivity_spectrum, show_plots


model0 = VAR(19)
model0.coef = np.eye(3, 3)
model0.coef[2, 0] = 0.8
model0.coef[2, 1] = 0.6
y = model0.simulate(10000).squeeze()

model = VAR(19)
model.fit(y)

dtf = connectivity("DTF", model.coef)
plot_connectivity_spectrum(dtf)
show_plots()
```

**Comment by mbillingr** [comment]
I took two ground-truth sources and showed that mixing them with volume conduction changes the DTF. This has nothing to do with ICA.

Honestly, I don't really see the point of the complicated simulation. You will have three different DTFs: ground truth, channels, and ICA sources. What is it you want to show?

**Comment by cbrnr** [comment]
> I took two ground-truth sources and showed that mixing them with volume conduction changes the DTF. This has nothing to do with ICA.

The problem is that some people might think that the ground truth is the channel space.

> Honestly, I don't really see the point of the complicated simulation. You will have three different DTFs: ground truth, channels, and ICA sources. What is it you want to show?

Ideally, the DTF estimated from ICA sources will resemble the original DTF. DTF from channels will be a mess. This would show that DTF on channels doesn't make sense.

**Comment by mbillingr** [comment]
> The problem is that some people might think that the ground truth is the channel space.

This applies to your argument as well.

> Ideally, the DTF estimated from ICA sources will resemble the original DTF. DTF from channels will be a mess. This would show that DTF on channels doesn't make sense.

My example already shows that DTF on channels is a mess. Maybe not a mess as such, but at least it shows a clear difference.
I'm afraid that adding ICA to the fray will not improve things. Most likely you will get a DTF that is different to both, the ground truth and the channels.

This simulation only shows if ICA can or cannot reliably reconstruct the original sources, but this is not the point of the discussion, is it?

**Comment by cbrnr** [comment]
> My example already shows that DTF on channels is a mess. Maybe not a mess as such, but at least it shows a clear difference.

That's right - your example answers the question "Is channel space DTF the same as source space DTF?" with a clear no.

We should dig a little deeper now. In this [opinion article](http://journal.frontiersin.org/article/10.3389/fncom.2014.00061/full), the authors claim that DTF is not influenced by volume conduction. Specifically, they write that DTF between any two channels is only non-zero if the phase between this channel pair is not zero (i.e. a non-zero phase implies no volume conduction). Does your example also address this claim?

**Comment by mbillingr** [comment]
I just realized, the example does not necessarily compare sources with channels. It can equally be interpreted as comparing signals originating from the channel site with and without volume conduction. In fact, I believe the mathematics is the same regardless where the sources are. There is always a mixing/conduction matrix. If the sources coincide with the channels the mixing matrix has ones on the diagonal. If the sources are somewhere else, the matrix is arbitrary.

> We should dig a little deeper now. In this opinion article, the authors claim that DTF is not influenced by volume conduction. Specifically, they write that DTF between any two channels is only non-zero if the phase between this channel pair is not zero (i.e. a non-zero phase implies no volume conduction). Does your example also address this claim?

We have a no connection from signal 0 to signal 1. After adding volume conduction (by adding a bit of one channel to the other and vice versa) we see an increase in DTF. From this result I would say that the DTF is actually sensitive to volume conduction. This claim is contrary to popular belief and will need deeper investigation.

**Comment by cbrnr** [comment]
> I just realized, the example does not necessarily compare sources with channels. It can equally be interpreted as comparing signals originating from the channel site with and without volume conduction. In fact, I believe the mathematics is the same regardless where the sources are. There is always a mixing/conduction matrix. If the sources coincide with the channels the mixing matrix has ones on the diagonal. If the sources are somewhere else, the matrix is arbitrary.

Yes, this is true. So we do not necessarily have to discuss sources vs. channels, which makes things complicated.

> We have a no connection from signal 0 to signal 1. After adding volume conduction (by adding a bit of one channel to the other and vice versa) we see an increase in DTF. From this result I would say that the DTF is actually sensitive to volume conduction. This claim is contrary to popular belief and will need deeper investigation.

I don't know - this article is the first time I've seen someone claim that DTF is insensitive to VC. I also don't think that this is popular belief. In [our JNE article](http://iopscience.iop.org/article/10.1088/1741-2560/10/4/046006), we even have a specific section on VC (section 2.3). There, we mention that VAR models do not model instantaneous connections (aka VC, zero-order term) - and we even specifically say that PDF and DTF do not take residual correlation into account, so they are influenced by VC.

I guess the next step is to find out if the statement that DTF is insensitive to VC is true or false. Your example already indicates that DTF is sensitive to VC. However, what about [that figure](http://www.frontiersin.org/files/Articles/67571/fncom-08-00061-HTML/image_m/fncom-08-00061-g001.jpg) where they overlaid a 20 Hz sine and no peak is visible in the DTF spectra (but a trough)? Can we construct a more formal example/proof that DTF is actually influenced by VC?

**Comment by cbrnr** [comment]
Consider the following example:

```{Python}
import numpy as np
from scot.var import VAR
from scot.connectivity import Connectivity
from scot.plotting import plot_connectivity_spectrum, show_plots


fs = 100  # sampling frequency
t = np.arange(0, 100, 1/fs)  # time vector, 100s long

# generate VAR process with no connectivity
model0 = VAR(19)
model0.coef = np.eye(3, 3)
y = model0.simulate(10000).squeeze()

model1 = VAR(19)
v = np.sin(2 * np.pi * 20 * t)  # overlay volume-conducted signal
model1.fit(y + v)

dtf1 = Connectivity(model1.coef).DTF()
plot_connectivity_spectrum(dtf1, fs=fs)
show_plots()
```

How does this _not_ show that DTF is influenced by VC? This is supposed to recreate the example from the opinion paper, where they didn't observe a peak in the off-diagonal elements. Here, the peaks are obvious. Either there's something wrong with my toy example, or with theirs.

![figure_1](https://cloud.githubusercontent.com/assets/4377312/14143765/3c2318b8-f68d-11e5-82a6-f72dda564202.png)

BTW, I wanted to plot the PSD on the diagonal, but couldn't figure out how - @mbillingr?

**Comment by mbillingr** [comment]
I agree that the PDC/DTF is based on VAR models which makes it very unlikely that they are really unperturbed by VC.

Somehow the discussion drifted from "It is okay to use ICA" to "DTF is not exactly what its inventors claim/want it to be"...

> Here, the peaks are obvious. Either there's something wrong with my toy example, or with theirs.

1. I think `model0` is not stable. Better move the poles into the unit circle by making the coefficients slightly lower.

2. Maybe that is because the example is too simple. In the opinion paper, they use real signals instead of simulated ones. Maybe the peak is overpowered by the connectivities in their example.

3. Our method of computing the DTF may be wrong. I don't think this is the case, but it is still a possibility we should rule out. 

> BTW, I wanted to plot the PSD on the diagonal, but couldn't figure out how - @mbillingr?

The `Workspace`'s plotting functions can do that. Outherwise you'd have to do it manually.


BTW,
Here is a semi-realistic mixing matrix for possible later use at some point. I'll create a gist with the code to create those later.
```
[[  1.44397803e-03,   1.54731486e-04,   1.97165553e-08,   2.28022549e-12],
 [ -1.34443780e-04,  -1.93051256e-03,  -8.58736026e-06,   2.00044820e-08],
 [  2.61207881e-08,  -3.04517246e-05,  -1.62597100e-03,  -2.80843517e-04],
 [  1.23244618e-10,   3.18171978e-06,   4.97017592e-04,  -4.87299659e-04],
 [  1.30958424e-03,  -1.80356736e-03,  -1.13891585e-03,  -7.66231900e-04]]
```
