### ISSUE TITLE
Wrong shapes in optimize_* functions?

### ISSUE THREAD

**Issue by cbrnr** [scot-dev/scot#180]
The docstring of `var.optimize_order` and `var.optimize_delta_bisection` defines the shape of the input data as `(n_trials, n_samples, n_channels)`. This is inconsistent with our conventions to have the data as `(n_trials, n_channels, n_samples)`. @mbillingr, I think that only the docstrings are wrong and the code is correct - could you please confirm?

**Comment by mbillingr** [comment]
Confirmed. The data is correctly treated as `(n_trials, n_channels, n_samples)` inside the functions.
