### ISSUE TITLE
Another SCOT

### ISSUE THREAD

**Issue by mbillingr** [scot-dev/scot#189]
First hit on google for "github scot":
https://github.com/sandialabs/scot

We are second :)

**Comment by cbrnr** [comment]
We: Sep 29 2013
They: Aug 24 2014

Only thing that bothers me is that we're not first on Google...

**Comment by mbillingr** [comment]
I guess that's because they are bigger, but I don't think it's a big deal. As soon as you google for something slightly more specific (such as 'scot eeg') we pop up first.

**Comment by cbrnr** [comment]
So should we do anything about it? I guess as long as no one complains we can ignore this issue, right?

**Comment by mbillingr** [comment]
right.
