### ISSUE TITLE
The issue of ws.plot_connectivity_surrogate

### ISSUE THREAD

**Issue by dongqunxi** [scot-dev/scot#191]
Dear @mbillingr and @cbrnr ,

I test one sample script 'connectivity.py' under the 'scot/examples/misc', I want to add the surrogate plots, when I use the functions related with 
surrogates (get_surrogate_connectivity and plot_connectivity_surrogate), it always comes out the 
error as ```  index 102 is out of bounds for axis 2 with size 100 ```. How to resolve it?
Thanks a lot.

**Comment by cbrnr** [comment]
Thanks for reporting this bug - I've fixed it in #192. It was just a dimension we forgot to swap. Please download and use the latest master until we release version 0.3, which will include this fix.

**Comment by dongqunxi** [comment]
Thanks @cbrnr, :+1: I will.
