### ISSUE TITLE
model order estimation using BIC method

### ISSUE THREAD

**Issue by dongqunxi** [scot-dev/scot#197]
Dear @cbrnr and @mbillingr ,
SCoT provides the way of VAR construction:
```ruby
mvar = scot.var.VAR(m)
```
I want to get 'm' by BIC method. I think SCoT has no this kind of function yet. So I tried to realize the optimized model order estimation using BIC, in the following gist: 
https://gist.github.com/dongqunxi/b23d1679b9bffa8e458c11f93bd8d6ff
I am not sure whether is correct, can you help me to check it? Thanks a lot!

**Comment by cbrnr** [comment]
Hi @dongqunxi! The code is correct assuming the equation for the BIC is correct, but there are some minor issues which I'd try to fix. According to Lütkepohl (2006), page 150, equation (4.3.9), the BIC (he calls it SC) can be computed as:

    SC(m) = ln(det(Sigma(m))) + ln(T) / T * m * K**2

`Sigma(m)` is the ML estimator of the noise covariance matrix, `m` is the VAR order, `T` is the sample size, and `K` is the dimension of the time series. Now you made the following assignments: `K` is the number of channels, `Sigma(m)` is `var.rescov`, `m` is the model order, and `T` is the number of samples times the number of trials (epochs). This sounds good to me (but you could remove the factor 2 in your calculation).

Regarding the implementation, I'd append the result to a list, so no need to initialize an array. Furthermore, you start with index 1, so the entry with index 0 is invalid - I'd only write valid values into the result list (so index 0 corresponds to m=1). And you should remove the `print` statement (which also doesn't work in Python 3).

Other than that, I think we should really add such a function (with more criteria) to SCoT - in which module would you put that @mbillingr?

**Comment by cbrnr** [comment]
I just saw that we've already discussed this in #130, only no one has had the time to implement it :-).

**Comment by dongqunxi** [comment]
Thanks @cbrnr , based on your suggestions, I updated the codes, how about it?  Hope SCoT will integrate the BIC function.
https://gist.github.com/dongqunxi/b23d1679b9bffa8e458c11f93bd8d6ff

**Comment by cbrnr** [comment]
Very nice! You don't have to convert `bic` to an array, `np.argmin` works on lists too. Yes, we will include these tests hopefully soon!

**Comment by dongqunxi** [comment]
Thanks for your help :-).
