### ISSUE TITLE
var copying mechanism

### ISSUE THREAD

**Issue by mbillingr** [scot-dev/scot#2]
are there bugs in copying var objects? maybe there is a better whay than passing an object to the workspace. instead we could pass the class and dict/list with arguments for the constructor.

**Comment by cle1109** [comment]
Is the current mechanism not working? How do you want to proceed with this issue?

**Comment by mbillingr** [comment]
I wanted to look into this a long time ago, but I didn't.

Maybe it's best if  we don't bother at the moment. Everything seems to be working.
