### ISSUE TITLE
obtaining n and m in plot_circular

### ISSUE THREAD

**Issue by mbillingr** [scot-dev/scot#3]
There is a bug in querying the number of components in plotting.plot_circular.

**Comment by mbillingr** [comment]
Damn, I can't remember what this bug is...

**Comment by cle1109** [comment]
We do have a test for `plot_circular` which works OK. The example also works as expected. Could it be related to `m` and `n`? If you can't remember what it was then maybe we should close this issue for now and come back to it if we encounter this bug again.

**Comment by mbillingr** [comment]
Well, the test simply calls the function to see if it runs without error. It's hard to actually test plotting functions.

I guess there may be a case where `n` and `m` are incorrectly inferred from the inputs. But you are right, if the bug is not obvious lets wait for it to pop up in practice.
