### ISSUE TITLE
Rename project to "scot"

### ISSUE THREAD

**Issue by cle1109** [scot-dev/scot#35]
Should we rename "SCoT" to "scot"? The only reason is that it is much more common to use all lowercase names, and everything else is a bit ugly :-). However, I don't know if this is even possible.

**Comment by kazemakase** [comment]
Actually it broke coveralls...

**Comment by cle1109** [comment]
Very good, thanks for noticing...

**Comment by kazemakase** [comment]
I think it's working again, but let's wait for the next pull request to be sure.

**Comment by kazemakase** [comment]
Hmm.. coveralls seems to have correctly received the results for PR #55: https://coveralls.io/r/scot-dev/scot?branch=master, but the bot did not comment on the PR...

**Comment by cle1109** [comment]
We've had some PRs since then and everything seems to be working - can we close this issue?

**Comment by kazemakase** [comment]
I think so :)
