### ISSUE TITLE
Use new-style classes

### ISSUE THREAD

**Issue by cle1109** [scot-dev/scot#41]
Would it break anything if scot used new-style classes?

**Comment by kazemakase** [comment]
No, since I believe classes are new-style by default in Python 3.

**Comment by cle1109** [comment]
So we could explicitly derive each class from `object`?

**Comment by kazemakase** [comment]
This is redundant in Python 3, but might improve compatibility with Python >=2.2.

So, yes, I think we should do that eventually.

We don't care that this does not work on Python 2.1 and below, do we?

**Comment by cle1109** [comment]
Right, I think we should focus on current Python versions (3.x and 2.7, probably also 2.6). Definitely not < 2.2. I'll take care of this change in a PR.

**Comment by kazemakase** [comment]
Thank you.

**Comment by cle1109** [comment]
Solved by #45.
