### ISSUE TITLE
Remove binica backend

### ISSUE THREAD

**Issue by cle1109** [scot-dev/scot#42]
I think we should remove the `binica` backend because (1) it is not Pythonic, (2) we have an excellent replacement from MNE (which BTW runs much faster anyway), (3) only exists on Linux, and (4) therefore breaks our tests on non-Linux platforms (I just ran the tests on my Mac and 5 tests failed because I don't have the `binica` executable).

If we remove it, this would automatically solve #32 and #37.

**Comment by kazemakase** [comment]
#43

**Comment by kazemakase** [comment]
#43
