### ISSUE TITLE
Set configuration in config.py and not in __init__.py

### ISSUE THREAD

**Issue by cle1109** [scot-dev/scot#44]
The configuration (e.g. default backend) should be set in `config.py` and not in `__init__.py`.

**Comment by kazemakase** [comment]
We should reconsider the configuration process entirely.
Does it make sense at all to have a config.py?
Should we try to load a user-specific config, if available?
How do other packages solve this?

**Comment by cle1109** [comment]
We're discussing a new config system in #69 and #70 - is this issue still relevant? If yes, we should move it to one of the two issues and close this one.

**Comment by mbillingr** [comment]
This issue is made obsolete by #70.
