### ISSUE TITLE
Upload to PyPI

### ISSUE THREAD

**Issue by cle1109** [scot-dev/scot#46]
Any plans on uploading scot to PyPI?

**Comment by agramfort** [comment]
would be cool

let me know if you need help

**Comment by cle1109** [comment]
I created PR #47 to address this issue - let's continue our discussion over there.

**Comment by kazemakase** [comment]
I think that is an excellent idea, now that we got rid of binica :)

**Comment by cle1109** [comment]
Merged by #47.
