### ISSUE TITLE
Set __version__

### ISSUE THREAD

**Issue by cle1109** [scot-dev/scot#48]
I think `__version__` is not set - I guess this should be set in `__init__.py` and read the version from the file `VERSION`.

**Comment by kazemakase** [comment]
How do other libraries handle setting of __version__?

**Comment by cle1109** [comment]
There are several options. I would go for option 4 [here](https://python-packaging-user-guide.readthedocs.org/en/latest/single_source_version.html#single-sourcing-the-version). That's how we do it in `setup.py` right now, so we could also read it in `scot/__init__.py`.

**Comment by kazemakase** [comment]
I'm not sure if it is good practice to parse a text file when importing the library.

**Comment by cle1109** [comment]
Not sure either - the caveat is of course that the file must be present. Alternatively, we could go with option 1, which involves setting `__version__` in `scot/__init__.py` and parsing this file in `setup.py` (which involves regexes).

**Comment by kazemakase** [comment]
Can't we import scot in setup.py to get the version?

**Comment by cle1109** [comment]
Sure, this should work. What do you think of #68?

**Comment by cle1109** [comment]
Resolved by #68.
