### ISSUE TITLE
VAR Model order estimation

### ISSUE THREAD

**Issue by dongqunxi** [scot-dev/scot#50]
Dear all,
I want to make a VAR model order estimation in my MEG data, how to do? Thanks!

**Comment by kazemakase** [comment]
The `VAR` object has a method for this: [optimize_order](http://scot-dev.github.io/scot-doc/api/scot/scot.html#scot.var.VAR.optimize_order).
This function uses cross-validation to determine the optimal model order. Alternatives to cross-validation are criteria such as [AIC](http://en.wikipedia.org/wiki/Akaike_information_criterion) or [BIC/SBC](http://en.wikipedia.org/wiki/Bayesian_information_criterion). These are more efficient to compute than cross-validation, but we have not implemented them.

**Comment by dongqunxi** [comment]
@kazemakase Thanks, I am testing 'optimize_oder'. 
'''ruby
mvar = scot.var.VAR(1)#Initialize VAR
mvar.optimize_order(label_ts, max_p=20)#label_ts'shape is (samples, channels, trials)
'''
get the results as following:
'''
....
 (9, 0.00041104371163276984),
 (10, 0.00037977463043710257),
 (11, 0.00036363522421652372),
 (12, 0.00034013376779647864),
...
'''
so I choose the model order corresponding the minimal msge, am I right?
Another aspect, the sampling of MEG data is 1017.25Hz, is it a factor to construct the MVAR model? 
Thanks!

**Comment by kazemakase** [comment]
> mvar = scot.var.VAR(1)#Initialize VAR
mvar.optimize_order(label_ts, max_p=20)#label_ts'shape is (samples, channels, trials)

Looks good to me.

> so I choose the model order corresponding the minimal msge, am I right?

Yes, that's right. The function also sets the VAR object's model order (`mvar.p`) to the value corresponding to the minimal msge.

> Another aspect, the sampling rate of MEG data is 1017.25Hz, is it a factor to construct the MVAR model?

Usually model order and sample rate are proportional. I.e. if you downsample by a factor of 2, you'll need half the model order. With your sampling rate I would not be surprised if you got a model order of 50. Of course that also depends on the data and I have no experience with MEG.

Finally, if you do not know which model order to expect in your application you can run `optimize_order` without specifying `max_p`. In this case the function keeps increasing the model order until the msge starts to increase. While this is not very robust to noise it can give you a rough idea about the model order you will need.

**Comment by dongqunxi** [comment]
Dear @kazemakase ,
Many thanks for your patience!

**Comment by kazemakase** [comment]
You're welcome :)
