### ISSUE TITLE
One question about the function 'optimize_order'

### ISSUE THREAD

**Issue by dongqunxi** [scot-dev/scot#51]
Dear @kazemakase ,

When I send the data as (samples, channels) to the ```optimize_order``` function, it meets an error,
```ruby
IndexError: tuple index out of range
``` 
but the introduction of this function shows it also accepts data shape as (samples, channels). Am I right?

**Comment by kazemakase** [comment]
This might be a bug. Does it work if you pass the data as (samples, channels, 1)?

**Comment by dongqunxi** [comment]
@kazemakase , I tried, it still met the error:
```ruby
AssertionError
```
I think error resulted from:
```ruby
optimize_order line 98: assert (data.shape[2] > 1)
 ```

**Comment by kazemakase** [comment]
Right, sorry I was confused. The function needs at least two trials so it can compute the cross-validation.

Apparently the documentation is wrong and should be fixed. 
Also it might make sense to replace the `assert` with a more meaningful exception.

**Comment by dongqunxi** [comment]
It is my pleasure.
