### ISSUE TITLE
Use extended Infomax by default

### ISSUE THREAD

**Issue by cbrnr** [scot-dev/scot#53]
As mentioned in #49, SCoT should use extended Infomax by default (just like EEGLAB does).

**Comment by kazemakase** [comment]
Do we actually know extended Infomax is better?

**Comment by cle1109** [comment]
Not necessarily, but Extended Infomax is most often applied to EEG data (together with FastICA and SOBI) - see http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0030135. In this article, it looks like extended and standard Infomax yield very similar results. However, I argue for using the extended version by default for the simple reason that it is the default in EEGLAB and much more often applied to EEG data than the standard version.

**Comment by kazemakase** [comment]
If they are mostly similar it would actually be better to use the normal version... ;)

But I agree, most people think of the extended version when they hear Infomax, so it would be a socially reasonable default. Right?

**Comment by cle1109** [comment]
I guess so, although I'm sure there are reasons why people use Extended Infomax by default (at least the EEGLAB people will know).

**Comment by kazemakase** [comment]
If we switch to extended Infomax by default, what about these parameters:

    n_subgauss : int
        The number of subgaussian components. Only considered for extended
        Infomax.
    kurt_size : int
        The window size for kurtosis estimation. Only considered for extended
        Infomax.
    ext_blocks : int
        The number of blocks after which to recompute Kurtosis.
        Only considered for extended Infomax.


Another thoughtː
Maybe even more important than setting a new default might be to expose such backend arguments to the user.

**Comment by cle1109** [comment]
Good question. I just checked `runica.m` - obviously they do not even use the extended option by default...
