### ISSUE TITLE
Axes of epochs

### ISSUE THREAD

**Issue by cle1109** [scot-dev/scot#63]
I just noticed that the current format of epoched data (samples x channels x trials) is not compatible with scikit-learn. I don't know exactly why, but it only works if the axes are (trials x channels x samples). It seems like some consistency check asserts that the length of dimension 0 of X is equal to the length of y.

Would it be problematic if we change the format of epoched data or is it too deeply woven into SCoT? BTW, MNE also organizes epoched data as (trials x channels x samples).

**Comment by kazemakase** [comment]
I agree, we should change the data format for various reasons.

The data format is **very** deeply woven into SCoT and this is going to be one hell of a pull request.

It will also have significant impact on the API, so we should increase the version number of SCoT when this is eventually merged.

**Comment by cle1109** [comment]
OK. So to summarize, we will change the following two formats:

* 2D data needs to be changed to (n_chans, n_samples) - it is now (n_samples, n_chans)
* 3D data needs to be changed to (n_trials, n_chans, n_samples) - it is now (n_samples, n_chans, n_trials)

**Comment by kazemakase** [comment]
Indeed. We need to do:

- Change all routines that work with data
- Change all docstrings
- Identify all places where some functionality implicitly relies on the order
- Adjust unit tests

The typical procedure would be to change the tests first and then fix everything until the tests are satisfied. However, I'm not sure if our test coverage is sufficient to find all places that need to be changed.
I think it's better to manually check file by file and function by function.

When doing that we will review a great deal of the codebase. Which means that we will find many other things that should be changed too. How are we going to handle these? (make a list for later treatment?)

**Comment by cle1109** [comment]
Oh yes. On the other hand, we'll get to know a lot of code as you say, so that's a good thing :-).

Yes, let's create issues as we stumble upon things that need to be changed and are unrelated to the dimensions PR.

How do we actually implement the changes? Can we somehow reasonably split the work?

**Comment by kazemakase** [comment]
We could simply assign files to avoid merge conflicts. One commit per file, and we can both commit to the same branch.

I'd also propose to reverse the assignment for the unit tests. I.e. you do the tests for the parts that I refactor, and I do the tests for your code.

**Comment by cle1109** [comment]
OK, let's get to work then! Could you take care of assigning files? I like the idea of reversing the roles in the tests!

**Comment by cle1109** [comment]
cf #65

**Comment by cle1109** [comment]
Solved by #65.
