### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by mbillingr** [scot-dev/scot#71]
We should not forget to increase the version number after releasing a new version on PyPi.
Also, we should create according git tags.

**Comment by kazemakase** [comment]
Version increased, but we forgot to tag the release. Any chance we can find the correct commit?

**Comment by cle1109** [comment]
I don't understand - you mean the commit where you increased the version
number? We should create a change log and write down what we actually
changed in each version. Why did you increase the version?

**Comment by kazemakase** [comment]
When we put version 0.1.0 on pypi we should have created a release tag on git and increased the version number in the master branch.

We forgot to do that, so I increased the version number now. However, I don't know which commit corresponds to the 0.1.0 release, so I cannot add a tag.

**Comment by cle1109** [comment]
I don't know either. Let's make a tag for the next PyPI release. We should make use of some GitHub features, such as milestones.

**Comment by cle1109** [comment]
Since we're now using a tag for our next 0.2 release, I guess we can safely close this issue now?

**Comment by mbillingr** [comment]
I wonder if we should create a 0.1.1 tag before advancing to 0.2 to make it easier to find a version that uses the old data orientation.

Btw, how do we mark version in the repository between tags?
Scikit-learn seems to do it like this: `__version__ = '0.18.dev0'`

**Comment by cle1109** [comment]
Yes, good idea. Could you do that? Just to make sure, you don't want any more PRs merged before the transpose one, right?

And yes, let's adopt the scikit-learn convention. After the 0.1.1 version, we would work on 0.2.dev0. What does the last part `dev0` mean?

**Comment by mbillingr** [comment]
Ah, it's all in the comments :)

```
# PEP0440 compatible formatted version, see:
# https://www.python.org/dev/peps/pep-0440/
#
# Generic release markers:
#   X.Y
#   X.Y.Z   # For bugfix releases
#
# Admissible pre-release markers:
#   X.YaN   # Alpha release
#   X.YbN   # Beta release
#   X.YrcN  # Release Candidate
#   X.Y     # Final release
#
# Dev branch marker is: 'X.Y.dev' or 'X.Y.devN' where N is an integer.
# 'X.Y.dev0' is the canonical version of 'X.Y.dev'
#
__version__ = '0.18.dev0'
```

That's my interpretation:
`dev` simply marks the development branch but PEP0440 always wants a number, so they just call it `dev0`.

I think we don't need alpha, beta and release candidate versions. Let's stick to two numbers `X.Y` for releases and `X.Y.dev0` for the development branch:
- `X` is only increased on really big changes akin to a complete rewrite.
- `Y` marks new releases.

I imagine it could work like this:
Assume the master branch is at version `0.2.dev0` and we want to release version 0.2.

1. change `scot.__version__ = '0.2'`
2. create a github release (tag?) on this commit.
3. change `__version__ = '0.3.dev0'`

What do you think?

**Comment by cle1109** [comment]
Great! Let's do it! This means that since we want to release 0.1.1 before the big change, we should change the version to 0.1.1 right now, create a tag, and upload the package to PyPI. Then, we change the version to 0.2.dev0 and continue working on our transpose PR. Correct?

**Comment by mbillingr** [comment]
Correct.

**Comment by mbillingr** [comment]
I've implemented the changes. Here is the release: https://github.com/scot-dev/scot/releases/tag/0.1.1

**Comment by cle1109** [comment]
Awesome! Thanks @mbillingr - now we can go ahead, close this issue and work on 0.2.
