### ISSUE TITLE
Value of reducedim should be None instead of "no_pca"

### ISSUE THREAD

**Issue by cle1109** [scot-dev/scot#73]
When calling `mvarica` with the argument `reducedim="no_pca"`, I get an error in `pca`, because this function expects the argument to be `None` if no dimensions should be discarded.

I suggest we change the value of the `reducedim` argument in `mvarica` to `None` to be consistent with the `pca` function.

**Comment by cle1109** [comment]
OK, actually the problem is just that line 81 incorrectly tested for `no pca` instead of `no_pca`. I'll fix it in a PR.

**Comment by cle1109** [comment]
On a related note, is there a difference between performing no PCA vs. performing PCA and keeping all sources? This might impact our choice of arguments (and their values).

**Comment by cle1109** [comment]
And I just noticed that the function `cspvarica` sets `reducedim=np.inf` if no dimensions are to be discarded. We should make all of these functions consistent.

**Comment by kazemakase** [comment]
> On a related note, is there a difference between performing no PCA vs. performing PCA and keeping all sources? This might impact our choice of arguments (and their values).

Of course there is a difference between performing PCA and not performing PCA :) However, ICA should not care, *in theory*. In practice, there might be a difference. This option is mainly useful for comparing the method wwith the 'naiive' case of no PCA.

> And I just noticed that the function cspvarica sets reducedim=np.inf if no dimensions are to be discarded. We should make all of these functions consistent.

I'm not sure how consistent the functions can be. PCA-based dimensionality reduction can be specified in terms of variance reduction or number of components. For CSP only the number of components makes sense.

**Comment by cle1109** [comment]
Hm. In both methods we can choose to keep all components, so we could have an argument that specifies exactly this in a consistent way for all related functions (`mvarica`, `cspvarica`, `pca`, `csp`, ...). Can't we say that `None` means we keep all dimensions? That way, I don't have to think about if I need to set the percentage of retained variance (1) or the number of components (`np.inf`)?

**Comment by kazemakase** [comment]
`np.inf` could work for both functions, but I think `None` is more pythonic. It also feels sensible that setting `reducedim=None` should lead to no dimensionality reduction.

**Comment by cle1109** [comment]
Fixed by #74. #77 addresses the consistency issue.
