### ISSUE TITLE
Coding style

### ISSUE THREAD

**Issue by cbrnr** [scot-dev/scot#79]
We should try to adhere to a consistent coding style. I suggest we stick to what everyone else does, namely PEP8 and NumPy docstrings, such as scikit-learn (that's where I mainly look up style-related things if in doubt).

If you agree, I will create a PR after we're done with #65, the big one.

**Comment by kazemakase** [comment]
I do agree. All newer code adheres to PEP8 anyway, but there are still some old and ugly parts hidden away in the codebase.

API functions should absolutely use numpy docstrings. We could be less strict for internally used functions, though.
