### ISSUE TITLE
Stochastic Tests

### ISSUE THREAD

**Issue by mbillingr** [scot-dev/scot#8]
Some of the unittests rely on random data (randn) or functionality (ICA). Sometimes they fail just because of random variation. This should not happen.

FastICA supports a random seed, but how could we handle the BINICA wrapper?

**Comment by kazemakase** [comment]
I think this has been resolved by #43, but I'll keep it open for now as a reminder to check if all unit tests set a random seed...

**Comment by cle1109** [comment]
#89 implemented a random seed in our examples. Is this issue still relevant?

**Comment by mbillingr** [comment]
No, I don't think so.
