### ISSUE TITLE
Unify construction of VAR equations

### ISSUE THREAD

**Issue by mbillingr** [scot-dev/scot#94]
Currently, the functions `_construct_var_eqns` in varbase.py and `_construct_var_eqns_rls` in var.py share a lot of code.

I propose to construct the equations in one place.

There are at least two options:
 1. to have one function that can optionally create equations with and without RLS.
 2. let `_construct_var_eqns_rls` call `_construct_var_eqns` to construct the equations and then pack the RLS part on top.

**Comment by cle1109** [comment]
I'd go for option 1 and add an optional `rls=False` argument to the function `construct_var_eqns`.
