### ISSUE TITLE
Improve test coverage

### ISSUE THREAD

**Issue by mbillingr** [scot-dev/scot#96]
Not much to say. These are the worst covered files:

file | coverage | lines missed
--- | --- | ---
scot/varica.py | 71% | **26**
scot/plainica.py | 76 % | 6
scot/var.py | 78% | **31**
scot/backend_builtin.py | 85% | 3
scot/pca.py | 87% | 6
scot/varbase.py | 89% | **16**
scot/ooapi.py | 94% | **18**
scot/plotting.py | 96% | **10**

**Comment by cle1109** [comment]
I'm closing this for now. If we feel that we need to significantly increase our coverage again, let's just open a new issue/PR.
